---
apiVersion: v1
data: 
  md.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "RtEAZ8K4k"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "RtEAZ8K4k"
              },
              "expr": "system_cpu_usage{application=\"My Spring Boot Application\", instance=\"registration:8080\", job=\"Spring Boot Application input\"}",
              "refId": "A"
            }
          ],
          "title": "Panel Title",
          "type": "timeseries"
        }
      ],
      "schemaVersion": 36,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "New dashboard",
      "uid": "sFiA78F4z",
      "version": 1,
      "weekStart": ""
    }   
kind: ConfigMap
metadata:
  name: grafana

---
apiVersion: v1
data: 
  prometheus.yaml: |
    apiVersion: 1
    datasources:
     - name: Prometheus
       type: prometheus
       access: proxy
       url: http://prometheus.dev.svc.cluster.local:9090
       version: 1
       editable: false
kind: ConfigMap
metadata:
  name: prometheus  
  
  
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grapha
  name: grapha
spec:
  containers:
  - env:
    - name: GF_SECURITY_ADMIN_PASSWORD
      value: admin
    image: grafana/grafana-oss:8.5.2
    name: grapha
    ports:
    - containerPort: 3000
    resources: {}
    volumeMounts:
    - name: grafana
      mountPath: /usr/share/grafana/public/dashboards/md.json
      subPath: md.json
    - name: prometheus
      mountPath: /usr/share/grafana/conf/provisioning/datasources/prometheus.yaml
      subPath: prometheus.yaml  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: grafana
    configMap:
       name: grafana
  - name: prometheus
    configMap:
       name: prometheus      
status: {}  

---
apiVersion: v1
data: 
  prometheus.yaml: |
    scrape_configs:
      - job_name: 'Registration Service (DEV)'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['registration.dev.svc.cluster.local:8080']
            labels:
              application: 'Registration Service in the Dev Environment'
      - job_name: 'Summary Service (DEV)'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['summary.dev.svc.cluster.local:8080']
            labels:
              application: 'Summary Service in the Dev Environment'        
kind: ConfigMap
metadata:
  name: prometheus
  
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: prometheus
  name: prometheus
spec:
  containers:
  - image: prom/prometheus:v2.35.0
    name: prometheus
    ports:
    - containerPort: 9090
    args: ["--config.file", "/etc/prometheus/prometheus.yaml"]
    volumeMounts:
    - name: prometheus
      mountPath: /etc/prometheus/prometheus.yaml
      subPath: prometheus.yaml
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: prometheus
    configMap:
        name: prometheus
status: {}