{
 "title": "Prod Environment",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Registration Service Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{application=\"Registration Service in the Prod Environment\", instance=\"registration.prod.svc.cluster.local:8080\", job=\"Registration Service (Prod)\"}"
    }
   ]
  },
  {
   "title": "Summary Service Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "up{application=\"Summary Service in the Prod Environment\", instance=\"summary.prod.svc.cluster.local:8081\", job=\"Summary Service (Prod)\"}"
    }
   ]
  },
  {
   "title": "Registration Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "\r\nsystem_cpu_usage{application=\"Registration Service in the Prod Environment\", instance=\"registration.prod.svc.cluster.local:8080\", job=\"Registration Service (Prod)\"}"
    }
   ]
  },
  {
   "title": "Summary Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "\r\nsystem_cpu_usage{application=\"Summary Service in the Prod Environment\", instance=\"summary.prod.svc.cluster.local:8081\", job=\"Summary Service (Prod)\"}"
    }
   ]
  },
  {
   "title": "Registration Service Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"Registration Service in the Prod Environment\", id=\"direct\", instance=\"registration.prod.svc.cluster.local:8080\", job=\"Registration Service (Prod)\"}"
    }
   ]
  },
  {
   "title": "Registration Service Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"Summary Service in the Prod Environment\", id=\"direct\", instance=\"summary.prod.svc.cluster.local:8081\", job=\"Summary Service (Prod)\"}"
    }
   ]
  }
 ]
}