apiVersion: v1
data: 
  prometheus.yaml: |
    scrape_configs:
      - job_name: 'Spring Boot Application input'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['registration:8080']
            labels:
              application: 'My Spring Boot Application'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus