---
apiVersion: v1
data: 
  prometheus.yaml: |
    scrape_configs:
      - job_name: 'Registration Service (DEV)'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['registration.dev.svc.cluster.local:8080']
            labels:
              application: 'Registration Service in the Dev Environment'
      - job_name: 'Summary Service (DEV)'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['summary.dev.svc.cluster.local:8080']
            labels:
              application: 'Summary Service in the Dev Environment'        
kind: ConfigMap
metadata:
  name: prometheus
  
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: prometheus
  name: prometheus
spec:
  containers:
  - image: prom/prometheus:v2.35.0
    name: prometheus
    ports:
    - containerPort: 9090
    args: ["--config.file", "/etc/prometheus/prometheus.yaml"]
    volumeMounts:
    - name: prometheus
      mountPath: /etc/prometheus/prometheus.yaml
      subPath: prometheus.yaml
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: prometheus
    configMap:
        name: prometheus
    #defaultMode: 0744
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grapha
  name: grapha
spec:
  containers:
  - env:
    - name: GF_SECURITY_ADMIN_PASSWORD
      value: admin
    image: grafana/grafana-oss:8.5.2
    name: grapha
    ports:
    - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}